/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * ثبت‌نام کاربر جدید
         * @description اولین کاربری که در کل پلتفرم ثبت‌نام کند خودکار owner (مالک پلتفرم) می‌شود.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    /**
                     * @example {
                     *       "email": "shop@example.com",
                     *       "password": "SuperSecret123"
                     *     }
                     */
                    "application/json": {
                        /** Format: email */
                        email: string;
                        /** Format: password */
                        password: string;
                    };
                };
            };
            responses: {
                /** @description ثبت‌نام موفق */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthTokenResponse"];
                    };
                };
                400: components["responses"]["BadRequest"];
                /** @description این ایمیل قبلاً ثبت‌نام کرده است. */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** ورود با ایمیل/پسورد */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    /**
                     * @example {
                     *       "email": "shop@example.com",
                     *       "password": "SuperSecret123"
                     *     }
                     */
                    "application/json": {
                        /** Format: email */
                        email: string;
                        /** Format: password */
                        password: string;
                    };
                };
            };
            responses: {
                /** @description ورود موفق */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthTokenResponse"];
                    };
                };
                400: components["responses"]["BadRequest"];
                /** @description ایمیل یا پسورد اشتباه است. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description حساب غیرفعال شده است. */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api-keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** لیست کلیدهای API من */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["ApiKey"][];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        /** ساخت کلید API جدید */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    /**
                     * @example {
                     *       "name": "سرور تولید"
                     *     }
                     */
                    "application/json": {
                        name: string;
                    };
                };
            };
            responses: {
                /** @description توکن کامل فقط همین یک‌بار نمایش داده می‌شود */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiKeyCreated"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api-keys/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** باطل کردن یک کلید API */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description باطل شد (بدون بدنه) */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** لیست محصولات من + محصولات سراسری */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["Product"][];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        /** ساخت محصول جدید */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    /**
                     * @example {
                     *       "name": "کرم مرطوب‌کننده",
                     *       "descriptionText": "حجم ۵۰ میلی‌لیتر، قیمت ۲۵۰ هزار تومان"
                     *     }
                     */
                    "application/json": {
                        name: string;
                        shortCode?: string;
                        descriptionText: string;
                    };
                };
            };
            responses: {
                /** @description ساخته شد */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            product?: components["schemas"]["Product"];
                        };
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** جزئیات یک محصول */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            product?: components["schemas"]["Product"];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** ویرایش/فعال-غیرفعال کردن محصول (فقط مالک محصول، نه محصولات سراسری) */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    /**
                     * @example {
                     *       "isActive": false
                     *     }
                     */
                    "application/json": {
                        name?: string;
                        descriptionText?: string;
                        isActive?: boolean;
                    };
                };
            };
            responses: {
                /** @description به‌روزرسانی شد */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            product?: components["schemas"]["Product"];
                        };
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        trace?: never;
    };
    "/contacts/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * آپلود اکسل مخاطبین از طریق API
         * @description multipart/form-data با فیلد file (.xlsx/.xls). ستون نام/شماره را می‌توانید صریح با nameColumnIndex/phoneColumnIndex بدهید، وگرنه از روی سرنویس‌های رایج فارسی/انگلیسی خودکار حدس زده می‌شود.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "multipart/form-data": {
                        /** Format: binary */
                        file: string;
                        /** @description اختیاری — مخاطبین به این محصول متصل می‌شوند */
                        productId?: string;
                        /** @description جایگزین productId؛ shortCode محصول */
                        productCode?: string;
                        /** @description اندیس ستون نام (از ۰)؛ اختیاری */
                        nameColumnIndex?: number;
                        /** @description اندیس ستون شماره (از ۰)؛ اختیاری */
                        phoneColumnIndex?: number;
                    };
                };
            };
            responses: {
                /** @description نتیجه import */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "totalRows": 120,
                         *       "imported": 110,
                         *       "duplicates": 6,
                         *       "invalid": 4,
                         *       "failed": 0,
                         *       "totalContactsNow": 430
                         *     }
                         */
                        "application/json": components["schemas"]["ImportResult"];
                    };
                };
                /** @description فایل ارسال نشده، قابل خواندن نبود، یا ستون‌ها قابل تشخیص نبودند */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/campaigns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** لیست کمپین‌های من */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["Campaign"][];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        /** ساخت کمپین جدید (draft) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    /**
                     * @example {
                     *       "name": "کمپین بهاره",
                     *       "productId": "b1f2c3d4-5678-90ab-cdef-1234567890ab"
                     *     }
                     */
                    "application/json": {
                        /** @description نام دلخواه کمپین (اختیاری) */
                        name?: string;
                        /** @description شناسه‌ی محصولی که این کمپین برایش ساخته می‌شود */
                        productId: string;
                    };
                };
            };
            responses: {
                /** @description ساخته شد (در وضعیت draft) */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            campaign?: components["schemas"]["Campaign"];
                        };
                    };
                };
                /** @description productId نامعتبر یا متعلق به شما نیست */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/campaigns/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** جزئیات و پیشرفت یک کمپین */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            campaign?: components["schemas"]["Campaign"];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/campaigns/{id}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** شروع ارسال کمپین (در پس‌زمینه) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description شروع شد؛ پیشرفت را از GET /campaigns/{id} دنبال کنید */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message?: string;
                            campaignId?: string;
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
                409: components["responses"]["Conflict"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/campaigns/{id}/pause": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * توقف موقت کمپین در حال اجرا
         * @description بلافاصله متوقف نمی‌شود؛ قبل از ارسال پیام بعدی، حلقه‌ی ارسال وضعیت را چک و متوقف می‌کند.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description متوقف شد */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message?: string;
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
                /** @description فقط کمپین در حال اجرا قابل توقف است */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/campaigns/{id}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** ادامه‌ی کمپین متوقف‌شده — دقیقاً از همان مخاطب باقیمانده */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ادامه پیدا کرد */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message?: string;
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
                /** @description فقط کمپین متوقف‌شده قابل ادامه است */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/campaigns/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** لغو کامل کمپین (غیرقابل بازگشت) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description لغو شد */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message?: string;
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
                /** @description کمپین از قبل تمام یا لغو شده است */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/conversations/active": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** مکالمات فعال (در حال گفتگوی خودکار با AI) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["Conversation"][];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/conversations/waiting": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** مکالمات منتظر پاسخ من (ارجاع‌شده به انسان) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["WaitingConversation"][];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/conversations/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** تاریخچه کامل یک مکالمه */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            conversation?: components["schemas"]["Conversation"];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/conversations/{id}/reply": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** پاسخ دستی به یک مکالمه‌ی ارجاع‌شده — مستقیماً به بازو می‌رود */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    /**
                     * @example {
                     *       "text": "سلام، بله موجوده. ارسالش رایگانه."
                     *     }
                     */
                    "application/json": {
                        text: string;
                    };
                };
            };
            responses: {
                /** @description ارسال شد */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            ok?: boolean;
                        };
                    };
                };
                /** @description متن خالی است یا مخاطب chat_id بازو ندارد */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/conversations/{id}/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** پایان ارجاع — مکالمه به AI برمی‌گردد و دوباره خودکار پاسخ می‌دهد */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            conversation?: components["schemas"]["Conversation"];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** لیست سفارش‌های من */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["Order"][];
                            summary?: {
                                completed?: number;
                                active?: number;
                                cancelled?: number;
                            };
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** جزئیات یک سفارش */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            order?: components["schemas"]["Order"];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/referrals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** لیست مکالمات ارجاع‌شده */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["Referral"][];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dashboard/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** خلاصه‌ی کامل داشبورد در یک درخواست */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DashboardSummary"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dashboard/statistics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** آمار با فیلتر بازه‌ی زمانی */
        get: {
            parameters: {
                query?: {
                    /** @description رزرو شده برای نسخه‌ی بعدی */
                    from?: string;
                    /** @description رزرو شده برای نسخه‌ی بعدی */
                    to?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DashboardStatistics"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** [فقط مالک پلتفرم] لیست همه‌ی کاربران */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["User"][];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api-keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** [فقط مالک] همه‌ی کلیدهای API + خلاصه فعالیت هرکدام */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["AdminApiKeySummary"][];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/activity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** [فقط مالک] لاگ کامل فعالیت، با فیلتر و صفحه‌بندی */
        get: {
            parameters: {
                query?: {
                    /** @description فقط فعالیت این کاربر */
                    userId?: string;
                    /** @description فقط فعالیت این کلید API */
                    apiKeyId?: string;
                    page?: number;
                    pageSize?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PaginatedAdminActivity"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            /** @description پیام خطای قابل‌نمایش به کاربر */
            error: string;
        };
        /** @description فیلدهای عمومی و امن کاربر — passwordHash هرگز در هیچ پاسخی برنمی‌گردد. */
        User: {
            /** Format: uuid */
            id?: string;
            /** Format: email */
            email?: string;
            isOwner?: boolean;
            isActive?: boolean;
            /** Format: date-time */
            createdAt?: string;
        };
        AuthTokenResponse: {
            /** @description JWT برای استفاده در Authorization: Bearer */
            token?: string;
            user?: components["schemas"]["User"];
        };
        /** @description keyHash (هش SHA-256 کل توکن) هرگز در هیچ پاسخی برنمی‌گردد؛ فقط این فیلدهای امن. */
        ApiKey: {
            /** Format: uuid */
            id?: string;
            name?: string;
            /** @example abai_live_9f6e817c... */
            keyPrefix?: string;
            isActive?: boolean;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            lastUsedAt?: string | null;
        };
        ApiKeyCreated: components["schemas"]["ApiKey"] & {
            /**
             * @description توکن کامل — فقط همین یک‌بار نمایش داده می‌شود.
             * @example abai_live_9f6e817cb2a145f0...
             */
            token?: string;
            warning?: string;
        };
        Product: {
            /** Format: uuid */
            id?: string;
            name?: string;
            shortCode?: string;
            descriptionText?: string;
            isActive?: boolean;
            /** @description null یعنی محصول سراسری (global) و همه‌ی کاربران می‌بینندش */
            userId?: string | null;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        CampaignProgress: {
            total?: number;
            processed?: number;
            successful?: number;
            failed?: number;
            pending?: number;
            percentage?: number;
        };
        Campaign: {
            /** Format: uuid */
            id?: string;
            name?: string | null;
            /** @enum {string} */
            status?: "draft" | "running" | "paused" | "completed" | "cancelled";
            /** Format: uuid */
            productId?: string;
            product?: {
                id?: string;
                name?: string;
            } | null;
            progress?: components["schemas"]["CampaignProgress"];
            /** @description آیا همین الان در پس‌زمینه در حال ارسال است */
            running?: boolean;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            startedAt?: string | null;
            /** Format: date-time */
            pausedAt?: string | null;
            /** Format: date-time */
            completedAt?: string | null;
            /** Format: date-time */
            cancelledAt?: string | null;
        };
        Contact: {
            /** Format: uuid */
            id?: string;
            name?: string;
            /** @example 989123456789 */
            phone?: string;
            /** @enum {string} */
            status?: "pending" | "sent" | "failed" | "no_bale";
            /** Format: date-time */
            sentAt?: string | null;
            errorMessage?: string | null;
        };
        Message: {
            /** Format: uuid */
            id?: string;
            /** @enum {string} */
            sender?: "user" | "ai" | "human";
            text?: string;
            /** Format: date-time */
            createdAt?: string;
        };
        Conversation: {
            /** Format: uuid */
            id?: string;
            contactId?: string;
            productId?: string | null;
            /** @enum {string} */
            state?: "active" | "completed" | "abandoned";
            needsHuman?: boolean;
            /** Format: date-time */
            escalatedAt?: string | null;
            escalationReason?: string | null;
            contact?: components["schemas"]["Contact"];
            product?: components["schemas"]["Product"];
            messages?: components["schemas"]["Message"][];
        };
        WaitingConversation: components["schemas"]["Conversation"] & {
            /** @description چند دقیقه از ارجاع می‌گذرد */
            waitingMinutes?: number | null;
        };
        Order: {
            /** Format: uuid */
            id?: string;
            conversationId?: string;
            /** @enum {string} */
            status?: "completed";
            /** Format: date-time */
            createdAt?: string;
            conversation?: {
                contact?: components["schemas"]["Contact"];
                product?: components["schemas"]["Product"];
            };
        };
        Referral: {
            conversationId?: string;
            contact?: components["schemas"]["Contact"];
            product?: components["schemas"]["Product"];
            /** @enum {string} */
            status?: "normal" | "needs_review" | "referred" | "resolved";
            reason?: string | null;
            /** Format: date-time */
            escalatedAt?: string | null;
            latestMessages?: components["schemas"]["Message"][];
        };
        ImportResult: {
            totalRows?: number;
            imported?: number;
            duplicates?: number;
            invalid?: number;
            failed?: number;
            /** @description کل مخاطبین این کاربر بعد از این import */
            totalContactsNow?: number;
        };
        ActivityLogEntry: {
            id?: string;
            /** @example campaign_started */
            action?: string;
            /** @example campaign */
            resourceType?: string;
            resourceId?: string | null;
            /** @description JSON string با جزئیات کمکی */
            metadata?: string | null;
            /** Format: date-time */
            createdAt?: string;
        };
        DashboardSummary: {
            campaigns?: {
                active?: number;
                total?: number;
                recent?: components["schemas"]["Campaign"][];
            };
            messages?: {
                sent?: number;
                failed?: number;
                pending?: number;
                noBale?: number;
            };
            conversations?: {
                active?: number;
                waitingForResponse?: number;
            };
            referrals?: number;
            orders?: {
                completed?: number;
            };
            products?: {
                active?: number;
            };
            recentActivity?: components["schemas"]["ActivityLogEntry"][];
        };
        DashboardStatistics: {
            messagesToday?: number;
            messagesThisWeek?: number;
            messagesThisMonth?: number;
            /** @description درصد (۰ تا ۱۰۰) */
            successRate?: number;
            failureRate?: number;
            activeCampaigns?: number;
            activeConversations?: number;
            waitingForResponse?: number;
            referrals?: number;
            completedOrders?: number;
        };
        AdminApiKeySummary: components["schemas"]["ApiKey"] & {
            user?: components["schemas"]["User"];
            /**
             * @example {
             *       "product_created": 3,
             *       "campaign_started": 5,
             *       "contacts_imported": 2
             *     }
             */
            activitySummary?: {
                [key: string]: number;
            };
        };
        AdminActivityEntry: components["schemas"]["ActivityLogEntry"] & {
            user?: components["schemas"]["User"];
            apiKey?: components["schemas"]["ApiKey"];
        };
        PaginatedAdminActivity: {
            data?: components["schemas"]["AdminActivityEntry"][];
            page?: number;
            pageSize?: number;
            total?: number;
            totalPages?: number;
        };
    };
    responses: {
        /** @description درخواست نامعتبر — فیلد الزامی خالی است یا مقدار داده‌شده نادرست است. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": "فیلدهای name و descriptionText الزامی هستند."
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description توکن ارسال نشده، نامعتبر، منقضی یا باطل‌شده است. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": "توکن احراز هویت ارسال نشده (Authorization: Bearer <token>)."
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description توکن معتبر است ولی اجازه‌ی این عملیات را ندارید. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": "این بخش فقط برای مالک پلتفرم در دسترس است."
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description منبع یافت نشد — یا اصلاً وجود ندارد، یا متعلق به کاربر دیگری است (این دو حالت عمداً یکسان جواب داده می‌شوند تا اطلاعاتی درباره‌ی داده‌ی کاربران دیگر درز نکند). */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": "محصول یافت نشد."
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description عملیات با وضعیت فعلی منبع در تعارض است. */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": "این کمپین از قبل در حال اجراست."
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
